### ISSUE TITLE
希望增加文泉书局的适配

### ISSUE THREAD

**Issue by zynfly** [systemmin/kill-doc#2]
https://wqbook.wqxuetang.com/

购买的电子书只能在线看，官方的阅读器老难用了。

**Comment by systemmin** [comment]
可以，后面抽空增加。但是这种电子书下载可能比较慢哦！因为内容太多多了，动辄都是几百页。脚本处理将会内容分为两种格式：图片PDF和纯文本txt文件

**Comment by zynfly** [comment]
嗯嗯，纯图pdf就够了。他官方的txt好像也有问题。

**Comment by systemmin** [comment]
忘了问你那个书是什么格式PDF还是epub格式，PDF应该可以了

**Comment by zynfly** [comment]
是PDF的

**Comment by systemmin** [comment]
更新脚本v2.2

**Comment by zynfly** [comment]
d=(´▽｀)=b   强大  👍👍👍

**Comment by zynfly** [comment]
发现BUG，每次自动预览30页左右会回到第一页重新开始预览。

**Comment by zynfly** [comment]
已通过二维码赞助100元，供买书测试。😄

**Comment by systemmin** [comment]
收到

**Comment by systemmin** [comment]
已更新再试试 v2.3

**Comment by zynfly** [comment]
![image](https://github.com/systemmin/kill-doc/assets/14913548/e6de775e-f06c-4810-9516-89fb3b42b848)
会出现这个  大概300多页的时候出现的

**Comment by systemmin** [comment]
出现这个页面还会滚动吗？还是说一直停留在这里了，还有没有其他问题

**Comment by zynfly** [comment]
出现这个就一直停在这儿了 
 然后能不能加一个这个预览下载的起止页  例如从 1 到 50   51 到 100  分段下载 然后再手工合并呗   这个书太大 下载容易到一半就掉登录

**Comment by systemmin** [comment]
我们的想法不谋而合，可能要明天才能更新

**Comment by zynfly** [comment]
好的好的

**Comment by zynfly** [comment]
![image](https://github.com/systemmin/kill-doc/assets/14913548/74216b5e-ad62-41a4-99ef-1848399b26d4)
我暂时先放弃了，等你更新

**Comment by systemmin** [comment]
更新脚本2.4，左上角选择好页码在点击自动预览

**Comment by zynfly** [comment]
已测试，确实可以分段预览了，现在有几个问题：
1.跳转到第几页开始预览，下载的pdf第一页是空白页
2.整本书最后一段（包含封底，大概100多页），预览完成，下载pdf缺少封底，我又单独预览最后两页重新下载回来的封底
3.wqbook.wqxuetang.com/api/v7/read/record/save  这个借口请求过多会出错，我现在使用F12调试功能给他屏蔽掉了

**Comment by systemmin** [comment]
把鼠标放在浏览器地址栏，键盘直接按F12可以打开。
第二种随便找个页面打开控制台，修改地址栏回车。
你上面说的问题我先测试一下

**Comment by systemmin** [comment]
> 已测试，确实可以分段预览了，现在有几个问题： 1.跳转到第几页开始预览，下载的pdf第一页是空白页 2.整本书最后一段（包含封底，大概100多页），预览完成，下载pdf缺少封底，我又单独预览最后两页重新下载回来的封底 3.wqbook.wqxuetang.com/api/v7/read/record/save 这个借口请求过多会出错，我现在使用F12调试功能给他屏蔽掉了

已更新v2.5 

- 198页测试15分钟左右全部下载。
- 空白页，缺页问题已解决。
- 若出现自动预约也未自动加载 `F5` 刷新

**Comment by zynfly** [comment]
> ![image](https://private-user-images.githubusercontent.com/14913548/337516407-74216b5e-ad62-41a4-99ef-1848399b26d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjcwMjcsIm5iZiI6MTcxNzgyNjcyNywicGF0aCI6Ii8xNDkxMzU0OC8zMzc1MTY0MDctNzQyMTZiNWUtYWQ2Mi00MWE0LTk5ZWYtMTg0ODM5OWIyNmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA2MDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NjgzNjAyNTEwOGFmM2M1NDdhYjZiMTQ0NzMwYWJjOTI1YzExMzk5ODg5OGU3OWU2NWM5ODk1ZWNjOTc5ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nrFTQmpqxarGfV5dJmqZdUNKtmxCOSxfn6hjtltmXhk) 我暂时先放弃了，等你更新

出现这个之后，点击停止预览，然后点击下载pdf，下载的pdf全是空白页。

是不是把范围放到工具里面，写上起止页码，到页码自动停止好一点？

**Comment by systemmin** [comment]
> 下载的pdf全是空白页。

如果全是空白页，就不是页码问题。有可能内容太大溢出（猜测）。你预览之前先自动预览几页停止，下载看看有没有问题，没有问题再重新开始（F5）。还有就是找本800页的发我地址，我没找到有800多页的

**Comment by zynfly** [comment]
https://wqbook.wqxuetang.com/book/73985   
https://wqbook.wqxuetang.com/book/3529

都是600多页 700页的样子

**Comment by zynfly** [comment]
再次赞助100，请查收

**Comment by systemmin** [comment]
> https://wqbook.wqxuetang.com/book/73985 https://wqbook.wqxuetang.com/book/3529
> 
> 都是600多页 700页的样子
> 
> https://wqbook.wqxuetang.com/book/3201901
> 
> 这个900多页差不多1000页了

收到

**Comment by systemmin** [comment]
我测试最大页面容量在300左右，到达300浏览器就会卡顿，内存占用达到5G内存。所以建议范围在100-300直接可能最佳，下载最快

把之前的脚本关掉，通过新地址安装这个脚本 https://greasyfork.org/zh-CN/scripts/497405-wq

- 自动分页执行
- 第一个框框页码
- 第二个框框页面容量，就是每次加载多少页内容，例如100预览100页后会自动下载，不需要手动下载。
- 开始执行：只需点击一次，每加载100自动下载，然后自动刷新页面，从上次预览位置自动开始下载，直到下载所有内容**结束**

![wq](https://github.com/systemmin/kill-doc/assets/25001289/d39f3326-c72b-40ed-81bd-cdc3712fb048)

![wq2](https://github.com/systemmin/kill-doc/assets/25001289/d45f130e-b8bc-41b6-89d4-9dab5ff4ffae)

**Comment by systemmin** [comment]
有问题就点结束执行，刷新、开始执行

**Comment by zynfly** [comment]
可以可以 我去测试一下

**Comment by zynfly** [comment]
不太对劲，回来的这次是全屏黑。
![image](https://github.com/systemmin/kill-doc/assets/14913548/dbe4cd52-eb60-4b37-a1d2-f60aa06b78c8)
![image](https://github.com/systemmin/kill-doc/assets/14913548/2ef95282-07db-44c9-8e21-a5ca16f69cd8)

**Comment by zynfly** [comment]
![image](https://github.com/systemmin/kill-doc/assets/14913548/ae22f49b-8c5b-4790-a322-a3fe67b6dc0f)

**Comment by systemmin** [comment]
所有的都是黑屏？

**Comment by zynfly** [comment]
是的，我还在排查，更换浏览器也是黑的。

**Comment by systemmin** [comment]
https://f.ws59.cn/f/ebbzfukstyi 复制链接到浏览器打开

**Comment by systemmin** [comment]
我这里测试没有问题
1、谷歌浏览（不要使用极速版）
2、篡改猴（黑色的）https://www.crxsoso.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo
3、脚本

**Comment by zynfly** [comment]
我测试完了，发现是脚本管理器的问题。

如果使用猴子，没问题
用 adguard 当脚本管理器，可以正常加载，下载就是黑的

**Comment by systemmin** [comment]
> 我测试完了，发现是脚本管理器的问题。
> 
> 如果使用猴子，没问题
> 用 adguard 当脚本管理器，可以正常加载，下载就是黑的

只兼容猴子

**Comment by zynfly** [comment]
ok,现在用猴子没啥问题了，后面是分为两个插件用，还是会合并呢？

**Comment by systemmin** [comment]
目前暂时不合并吧，因为文泉这个和之前脚本差异太大
