### ISSUE TITLE
飞书下载已失效

### ISSUE THREAD

**Issue by IsaacZZhang** [systemmin/kill-doc#3]
@match        https://*.feishu.cn/space/*

当前飞书文档打开空间总览地址为 https://*.feishu.cn/drive/*，具体文档为https://*.feishu.cn/docx/*

**Comment by systemmin** [comment]
发个对应的文件地址 PPT，PDF，Excel 都可以

**Comment by wu0407** [comment]
飞书文档不支持？

**Comment by systemmin** [comment]
> 飞书文档不支持？.类似*.feishu.cn/wiki/

不支持，推荐一个插件
https://www.crxsoso.com/webstore/detail/ehkomhhcinhikfddnmklbloahaakploh
