### ISSUE TITLE
大佬能不能增加这个

### ISSUE THREAD

**Issue by Jusheanb** [systemmin/kill-doc#6]
aHR0cHM6Ly93d3cuZWxpYi5saW5r

**Comment by systemmin** [comment]
> aHR0cHM6Ly93d3cuZWxpYi5saW5r

好的先研究一下

**Comment by Jusheanb** [comment]
希望能做一个手动翻页，自动很多时候会卡住，容易被检测到

**Comment by systemmin** [comment]
> 希望能做一个手动翻页，自动很多时候会卡住，容易被检测到

那个平台，你自己其实可以改下脚本滚动时间

**Comment by Jusheanb** [comment]
可知，很多时候都会卡住，翻一两页就会卡住，用滚轮向上翻一下，又会翻一两页，如此反复循环

**Comment by systemmin** [comment]
> 可知，很多时候都会卡住，翻一两页就会卡住，用滚轮向上翻一下，又会翻一两页，如此反复循环

这个参数控制翻页时长，把页面容量改小，默认100，可以改成20或50（双击100选中可以修改）。还有如果上百页下载肯定会卡，把电脑没用的软件关一关，因为谷歌本身就很吃电脑内存

![image](https://github.com/user-attachments/assets/4a29a89f-9630-4d9c-93d2-cddc1d1651b3)

**Comment by Jusheanb** [comment]
ok,我测试一下；看看

**Comment by Jusheanb** [comment]
但很多时候，是在阅读前几页就会出现这种情况

**Comment by Jusheanb** [comment]
https://github.com/user-attachments/assets/38913146-57d9-4250-aae4-9639083443c6

就是这个效果

**Comment by systemmin** [comment]
更新脚本

**Comment by Jusheanb** [comment]
更新了吗，还是1.1.2

**Comment by systemmin** [comment]
![image](https://github.com/user-attachments/assets/2050b630-b864-4f43-974f-235ade009cd5)

**Comment by Jusheanb** [comment]
大佬书递，有问题，翻到第4页后，页面就会无规律乱跳

**Comment by systemmin** [comment]
> 大佬书递，有问题，翻到第4页后，页面就会无规律乱跳

上效果图

**Comment by Jusheanb** [comment]
https://github.com/user-attachments/assets/b24b0a10-7bea-4a42-a2e5-ab738b459185

**Comment by systemmin** [comment]
> 大佬书递，有问题，翻到第4页后，页面就会无规律乱跳

你把那个比例调小（100%），这个默认都是图片，你调大没有

**Comment by Jusheanb** [comment]
测试了一下，好像还是一样的效果

Uploading 屏幕录制 2024-09-29 111709.mp4…

**Comment by Jusheanb** [comment]
测试了一下，好像还是一样的效果
https://github.com/user-attachments/assets/18a5da46-561f-4f54-a558-a0f76c214fa5

**Comment by systemmin** [comment]
![image](https://github.com/user-attachments/assets/5f3b78aa-4f18-4857-a766-85324a193454)

**Comment by Jusheanb** [comment]
不行，脚本的计数页对了，实际翻页不对，一次还是调很多页

**Comment by systemmin** [comment]
> 不行，脚本的计数页对了，实际翻页不对，一次还是调很多页
你不用管它翻多少页面，你要看最终下载页面是不是对的，顺便把地址贴下

**Comment by Jusheanb** [comment]
https://www.elib.link/bookDetail?id=6171628345714490
最终下载的也不对，最终下载的是按照实际跳转下载的

**Comment by systemmin** [comment]
过几天更新

**Comment by systemmin** [comment]
> https://www.elib.link/bookDetail?id=6171628345714490 最终下载的也不对，最终下载的是按照实际跳转下载的

已解决

**Comment by Jusheanb** [comment]
测试了一下，已经可以完美适应了
