### ISSUE TITLE
请求适配网址

### ISSUE THREAD

**Issue by renxingblack** [systemmin/kill-doc#7]
在线office预览网页请求适配：
https://weboffice.qq.com/open/weboffice/pdf/UlZWUVNFTlphR1JWVnc9PV83OTc2YWM3Y2RlZGI3ZTFhMGIyN2Y1NTZkMTQ1ZDBiNF83YjhiNjZiMi05ZmFlLTQxNmItOWZiNS0zZjgxOWI0YzU5Y2I?_o_appId=b12ce56c53c044c1a392919df446ad95&_o_token=undefined&_o_sign=375763d23470566be8447ce8f6d2afb064c29a71&_o_t=1715052609114&_o_n=104a674e-a087-47dd-a4f0-4967bf69e8af&mode=simple&_o_insId=1
自己想另存为pdf都不可以，只能存一页，其余页不显示，请求大佬适配。
× 直接打印（可以打印一张）
× 打印选择—另存为PDF（只可以导出一张）

**Comment by renxingblack** [comment]
不止这一个的，有很多文件，我目前唯一的办法就是一张张截图（每份文件都是10几份）。
这个文件是微云分享的，很多学校的资料都是这样发下来，老师就是不给分享链接，只给预览的链接，让我们自己打印，但是我们也直接打印不了，所以看看能适配不。
这是微云的文件链接。
https://www.weiyun.com/document?fileId=RVVQSENZaGRVVw==_7976ac7cdedb7e1a0b27f556d145d0b4_7b8b66b2-9fae-416b-9fb5-3f819b4c59cb&officeType=pdf&tdsourcetag=s_weiyun_file

我自己也分享了一份，大佬您看看能适配不。
微云链接：https://share.weiyun.com/GNtzzcri
预览链接：https://www.weiyun.com/document?fileId=RlZQT0JXaG9VVg==_6c714153f0a739ae12b58dcd423dce4a_5ecda918-775b-4610-8dfb-0ecb85d58766&officeType=pdf&tdsourcetag=s_weiyun_file

**Comment by systemmin** [comment]
一个是腾讯一个微云是吧

https://weboffice.qq.com

https://www.weiyun.com

**Comment by systemmin** [comment]
更新5.5
